[build]
  publish = "."
  command = "echo 'No build needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' 
        https://apis.google.com 
        https://accounts.google.com
        https://cdn.tailwindcss.com 
        https://cdn.jsdelivr.net
        https://kit.fontawesome.com
        https://maps.googleapis.com;
      connect-src 'self' 
        https://apis.google.com 
        https://accounts.google.com
        https://www.googleapis.com;
      frame-src 'self' 
        https://accounts.google.com;
      img-src 'self' data: https: blob:;
      style-src 'self' 'unsafe-inline' 
        https://fonts.googleapis.com 
        https://cdn.tailwindcss.com;
      font-src 'self' 
        https://fonts.gstatic.com
        https://kit.fontawesome.com;
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  port = 9000
  publish = "."
  autoLaunch = true
